Repository ZenGuard-AI/fast-llm-security-guardrails, pull requests merged in 2024-06, with the labels that each got.

#38 [sdk] up the version and delete prints
  pyproject.toml
  zenguard/zenguard.py
Labels: bug

#39 [feature] add async detect and reporting for prompt_injection detector
  pyproject.toml
  tests/zenguard_e2e_test.py
  zenguard/zenguard.py
Labels: enhancement

#40 [bug] change post to get for report function
  pyproject.toml
  tests/zenguard_e2e_test.py
  zenguard/zenguard.py
Labels: bug

#41 [test] add github ruff formatting hook to ZenGuard client
  .pre-commit-config.yaml
  poetry.lock
  pyproject.toml
Labels: enhancement

#43 [zenguard client] OpenAI tests became a bit unstable
  poetry.toml
  pyproject.toml
  tests/conftest.py
  tests/openai_chat_e2e_test.py
  tests/zenguard_e2e_test.py
  zenguard/ai_clients/openai.py
  zenguard/zenguard.py
Labels: bug

#47 [docs] add public policies folder
  docs/policies/zenguard-red-chrome-extension-policy.md
Labels: documentation
